server:
  port: 8080
  servlet:
    context-path: /locations

spring:
  application:
    name: location-finder

location-service:
  url: https://servicodados.ibge.gov.br/api/v1/

postal-code-service:
  url: https://viacep.com.br/ws/

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000

